# ============================================
# 评测配置：
#   - 数据集hf路径
#   - 数据集split
#   - 数据集size
#   - 数据集模态
#   - 评测方式（multiple choice / generation / ...）
#   - 评测指标（accuracy / ...）
#   - 是否支持few_shot
#   - 选项编号形式（ABCD或1234...），判断对错时的标识(true/false或者1/0...)
# ============================================
dataset:
  name: ARC
  path: allenai/ai2_arc
  split: test
  size:
  modality: text-to-text
  fewshot_data_path: allenai/ai2_arc
  fewshot_data_file: null
  fewshot_data_split: validation
  cot_fewshot_data_path: null
  cot_fewshot_data_file: null
  cot_fewshot_data_split: null
  max_shot: 5
  default_task_list: ["ARC-Challenge", "ARC-Easy"]
task:
  - name: ARC-Challenge
    type: MultiChoice
    data_files: ["ARC-Challenge/test*.parquet"]
    question_key: question
    answer_key:
      choices: ""
      text: ""
    ground_truth_key: answerKey
    candidate_labels: [A, B, C, D, E]
    avalable_evaluate_tools: ["match_letter"]
  - name: ARC-Easy
    type: MultiChoice
    data_files: ["ARC-Easy/test*.parquet"]
    question_key: question
    answer_key:
      choices: ""
      text: ""
    ground_truth_key: answerKey
    candidate_labels: [A, B, C, D, E]
    avalable_evaluate_tools: ["match_letter"]
answer_extractor:
  - name: match_letter
    function: regex_match_letter
    args:
      additional_pattern: "{original_pattern}"
      match_index: 0
metrics:
  - name: accuracy
    function: accuracy
    args:
overall_metrics:
  - name: null
    function: null
    args:
      null
