dataset:
  name: CDialBias
  path: eval-anything/eval_anything/benchmarks/safedata/CDialBias.csv
  split: train
  size:
  modality: text-to-text
  default_task_list: ["CDialBias"]
  # /share/project/znh/eval/eval_anything/data
task:
  - name: CDialBias