dataset:
  name: Dice
  path: eval-anything/eval_anything/benchmarks/safedata/dices350_filtered.csv
  split: train
  size:
  modality: text-to-text
  default_task_list: ["Dice"]
  # /share/project/znh/eval/eval_anything/data
task:
  - name: Dice
